"""Render the opening shot's poster images (public/atlas/poster.webp, poster-portrait.webp).

The atlas shows these the moment the page loads, lined up exactly with the live map, which then
fades in over them (see src/data/atlas/poster.ts). They're renders of the app itself, so re-run
this whenever the opening view's look changes:

  npm run build && npm run start &          # or any running copy of the site
  python scripts/atlas/render_poster.py [--base http://localhost:3000]

Needs Playwright's Chromium (pip install playwright; playwright install chromium). The sizes,
fields of view and focal points come from src/data/atlas/poster.ts: keep POSTERS below in step.
The portrait poster is rendered as phones render the map (the low-power tier), the landscape
one as desktops do. Each also gets a tiny blurred copy, inlined in the page so something of the
city shows before the poster itself arrives (src/data/atlas/posterThumbs.ts, generated).
"""

import argparse
import base64
import io
import os
import time
from pathlib import Path

from PIL import Image
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "public" / "atlas"
THUMBS = ROOT / "src" / "data" / "atlas" / "posterThumbs.ts"
POSTERS = {
    "landscape": {"file": "poster.webp", "size": (2400, 1200), "phone": False, "thumb": (48, 24)},
    "portrait": {"file": "poster-portrait.webp", "size": (1000, 1830), "phone": True, "thumb": (24, 44)},
}


def write_thumbs():
    """The posters on disk, as tiny WebP data URLs, into posterThumbs.ts."""
    lines = []
    for name, spec in POSTERS.items():
        img = Image.open(OUT / spec["file"]).convert("RGB").resize(spec["thumb"], Image.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, "WEBP", quality=60)
        lines.append(f'  {name}: "data:image/webp;base64,{base64.b64encode(buf.getvalue()).decode()}",')
    THUMBS.write_text(
        "// Generated by scripts/atlas/render_poster.py: tiny copies of the posters, shown blurred\n"
        "// under them until they load.\n"
        "export const POSTER_THUMBS = {\n" + "\n".join(lines) + "\n};\n"
    )
    print(f"{THUMBS.name}: {THUMBS.stat().st_size} bytes")
ARGS = ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="http://localhost:3000")
    ap.add_argument("--only", choices=list(POSTERS))
    ap.add_argument("--settle", type=float, default=20, help="seconds to wait after the map is ready")
    ap.add_argument("--quality", type=int, default=70)
    ap.add_argument("--thumbs", action="store_true", help="only regenerate the inlined thumbnails")
    a = ap.parse_args()
    if a.thumbs:
        write_thumbs()
        return
    exe = os.environ.get("CHROMIUM")
    with sync_playwright() as p:
        b = p.chromium.launch(executable_path=exe, args=ARGS) if exe else p.chromium.launch(args=ARGS)
        for name, spec in POSTERS.items():
            if a.only and name != a.only:
                continue
            w, h = spec["size"]
            ctx = b.new_context(viewport={"width": w, "height": h}, device_scale_factor=1, is_mobile=spec["phone"],
                                has_touch=spec["phone"], reduced_motion="reduce")
            # Desktop tier: a desktop's core count (render machines are often small).
            if not spec["phone"]:
                ctx.add_init_script("Object.defineProperty(navigator, 'hardwareConcurrency', { get: () => 8 })")
            page = ctx.new_page()
            page.goto(f"{a.base}/atlas?poster={name}", wait_until="domcontentloaded", timeout=300000)
            page.wait_for_selector('.atlas[data-ready="1"]', timeout=900000)
            time.sleep(a.settle)
            # Capture mode (?poster=...) hands back one frame of the map alone.
            url = page.evaluate("() => window.__atlasCapture()")
            img = Image.open(io.BytesIO(base64.b64decode(url.split(",", 1)[1]))).convert("RGB")
            if img.size != (w, h):
                raise SystemExit(f"{name}: rendered {img.size}, expected {(w, h)}")
            out = OUT / spec["file"]
            img.save(out, "WEBP", quality=a.quality, method=6)
            print(f"{out.name}: {w}x{h}, {out.stat().st_size / 1024:.0f} KB")
            ctx.close()
        b.close()
    write_thumbs()


if __name__ == "__main__":
    main()
